sudo: required
install: true
language: go
go:
  - 1.8
deploy:
  provider: gae
  project: pulsecheck-167520
  keyfile: gce.json
  verbosity: debug
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_6951afb58799_key -iv $encrypted_6951afb58799_iv
  -in gce.json.enc -out gce.json -d
script: go test 

jobs:
  fast_finish: true 
notifications:
    slack: pulzchk:aUgiBENZweh7SFQofckYcabh
