sudo: required
install: true
language: go
go:
  - 1.8
deploy:
  provider: gae
  project: pulsecheck-167520
  keyfile: gce.json
  verbosity: debug
  skip_cleanup: true
env:
  global:
    - DBUSER=pulse 
    - DBPWD=pulsecheck 
    - DBADDR=23.236.60.151:3306
    - ELASTIC_URL=https://aade6f5cd32cedd31ee3a3c61384275f.us-central1.gcp.cloud.es.io:9243
    - ELASTIC_UNAME=elastic
    - ELASTIC_PWD=zcAIW0nyX6AOeBQNGEwFPXaA
before_install:
  - go get -v github.com/gorilla/context
  - openssl aes-256-cbc -K $encrypted_6951afb58799_key -iv $encrypted_6951afb58799_iv
     -in gce.json.enc -out gce.json -d
script: go test 
jobs:
  fast_finish: true 
notifications:
    slack: pulzchk:aUgiBENZweh7SFQofckYcabh
 p